### ISSUE TITLE
Convert News SEO to react

### ISSUE THREAD

**Issue by bintzandt** [Yoast/wpseo-news#619]
In order to successfully integrate News SEO in the new modal, we need to convert it to React and render it in the plugin.

Below is an image that shows how News SEO currently looks in the Metabox in our plugin:
<img width="801" alt="afbeelding" src="https://user-images.githubusercontent.com/8782235/75436870-8a8fe600-5955-11ea-8ed3-3e7552667571.png">

This is how it should look like in the new modal:
<img width="719" alt="afbeelding" src="https://user-images.githubusercontent.com/8782235/75436929-ad21ff00-5955-11ea-9066-4662dd7bc9a4.png">

## Tasks
- [ ] Create a form with the components from the new design (in React)
- [ ] Make sure to render hidden input fields via PHP that have the same IDs as those that are currently used
- [ ] Add logic to the input fields that change the value of the hidden input fields when their value changes (i.e. add an `onChange` event handler to all the input fields and update the hidden input field with the correct value)
	- [ ] Make sure that the server can still parse the content of the hidden input fields so keep the data format the same
	- [ ] Make sure that the fields are initialized using the value from the hidden input fields. This makes sure that the components keep their "state" when the modal is closed / the page is reloaded.
- [ ] Update the styling so it matches the new design
- [ ] Wrap everything in a `<Fill>` so that it can be placed in a `<Slot>` that we provide in the `Free` plugin
